version: '3'
services:
    muh_redis:
      container_name: muh_redis
      image: 'docker.io/bitnami/redis:6.0-debian-10'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
        - '6379:6379'
      volumes:
        - './data:/bitnami/redis/data'
    muh_bot:
      container_name: muh_bot
      build: . 
      env_file: 
        - '.env'
      volumes:
        - './data:/app/out'  