FROM python:latest

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY startup.py startup.py

RUN mkdir /usr/src/app/data
RUN mkdir /tmp/audio_dump

COPY top-1000-words.txt .

ENV AUDIO_DUMP_PATH "/tmp/audio_dump"
ENV DATA_FILE_PATH "/usr/src/app/data/data.json"
ENV WORD_DICT_PATH "top-1000-words.txt"

CMD [ "python", "./startup.py" ]