FROM golang:latest as builder

RUN apt-get update && apt-get -y install libopus-dev libopusfile-dev

WORKDIR /app
COPY go.mod .
COPY go.sum .
COPY main.go .
RUN go build -o main .

CMD ["/app/main"]

# Backend
FROM jrottenberg/ffmpeg:latest

RUN apt-get update && apt-get -y install libopus-dev libopusfile-dev

WORKDIR /app
COPY --from=builder /app/main main

RUN mkdir /tmp/audio_dump
RUN mkdir /app/sounds
COPY muh.mp3 /app/sounds/muh.mp3

ENV AUDIO_DUMP /tmp/audio_dump
ENV MUH_FILE_PATH /app/sounds/muh.mp3

ENTRYPOINT [ "/app/main" ]
